changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: Other Changes
      labels:
        - "*"
